name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'        

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set environment variables
      run: |
        echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> $GITHUB_ENV   

    - name: Build and tag NestJS Docker image
      run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dockerize-nest-app:latest -f dockerize-nest/Dockerfile .
    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockerize-nest-app:latest

      
   
   # - name: Run Docker Compose
   #   run:  docker-compose -f dockerize-nest-app/docker-compose.yaml up -d

