name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'        

    - name: Check Docker Compose version
      run: docker-compose --version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set environment variables
      run: |
        echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> $GITHUB_ENV   
    
    - name: Build Docker images with Docker Compose
      run: docker-compose -f dockerize-nest-app/docker-compose.yaml build

    - name: Push Docker images with Docker Compose
      run: docker-compose -f dockerize-nest-app/docker-compose.yaml  push

    - name: Run Docker Compose
      run:  docker-compose -f dockerize-nest-app/docker-compose.yaml up -d

